version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app        
    ports:
      - "5000:5000"     
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ebook-store
    ports:
      - "5431:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network
    
  frontend:
    build: ./frontend
    volumes:
     - ./frontend:/app
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
      - WATCHPACK_POLLING=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pg_data: