version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app        
    ports:
      - "5000:5000"     
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ebook-store
    ports:
      - "5431:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: